version: '3.3'

services:
    www:
        restart: always
        image: nginx:alpine
        volumes:
          - ./www/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
          - 81:80
        depends_on:
          - backend
          - frontend

    backend:
        restart: always
        build:
            context: ./projectx-back
        # user: 1000:1000
        environment:
            DB_NAME: projectx
            DB_PASSWORD: password

    db:
        restart: always
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: Europe/Paris
            MYSQL_ROOT_PASSWORD: Yobar92110
            MYSQL_DATABASE: projectx
            MYSQL_USER: my_shop
            MYSQL_PASSWORD: password
        volumes:
            - /home/yobar/projectx/db:/var/lib/mysql:rw

    frontend:
        restart: always
        build:
            context: ./projectx-front
        # user: 1000:1000