version: '3.3'

services:
    www:
        image: nginx:alpine
        # volumes:
        #   - ./www/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
          - 80:80
        depends_on:
          - backend
          - frontend

    backend:
        build:
            context: ./projectx-back
        user: 1000:1000
        # volumes:
        #     - ./projectx-back:/usr/src/projectx-backend:rw
        environment:
            DB_NAME: projectx
            DB_PASSWORD: password

    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: Europe/Paris
            MYSQL_ROOT_PASSWORD: Yobar92110
            MYSQL_DATABASE: projectx
            MYSQL_USER: my_shop
            MYSQL_PASSWORD: password
        # volumes:
        #     - /home/yobar/projectx/db:/var/lib/mysql:rw

    frontend:
        image: node
        user: 1000:1000
        working_dir: /app
        volumes:
            - ./projectx-front:/app
        environment:
            NODE_ENV: development
        command: "npm run serve"