version: '3.3'

services:
    www:
        image: nginx:alpine
        volumes:
          - ./www/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - 80:80
        depends_on:
          - backend
          - frontend
          - db


    backend:
        build: ./projectx-back
        volumes:
            - .projectx-back:/app
        environment:
            DB_PASSWORD: password

    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: Europe/Paris
            MYSQL_ROOT_PASSWORD: Yobar92110
            MYSQL_DATABASE: projectx
            MYSQL_USER: my_shop
            MYSQL_PASSWORD: password
        volumes:
            - /tmp/projectx/db:/var/lib/mysql:rw

    frontend:
        image: node
        user: ${UID}:{UID}
        working_dir: /app
        volumes:
            - ./projectx-front:/app
        environment:
            NODE_ENV: development
        command: "npm run serve"
        ports:
            - 80:80
